export const defaultInputs = [
    {
        name: "Subject",
        attributeName: "se_subjects",
        data: [
            "Social Science",
            "Science",
            "Mathematics",
            "Hindi",
            "English",
            "History",
            "Geography",
        ],
    },
    {
        name: "Class",
        attributeName: "se_gradeLevels",
        data: [
            "Class 1",
            "Class 2",
            "Class 3",
            "Class 4",
            "Class 5",
            "Class 6",
            "Class 7",
            "Class 8",
            "Class 9",
            "Class 10",
        ],
    },
    {
        name: "Medium",
        attributeName: "se_mediums",
        data: [
            "english",
            "hindi"
        ],
    },
    {
        name: "Board/Organisation",
        attributeName: "se_boards",
        data: [
            "CBSE/NCERT",
            "bosem",
            "cbse (delhi)",
            "cisce",
            "igot-health",
            "national",
            "ncert",
            "ncte",
            "nios",
            "other",
            "others",
            "state (andhra pradesh)",
            "state (arunachal pradesh)",
            "state (assam)",
            "state (bihar)",
            "state (chandigarh)",
            "state (chhattisgarh)",
            "state (delhi)",
            "state (goa)",
            "state (gujarat)",
            "state (haryana)",
            "state (himachal pradesh)",
            "state (jammu and kashmir)",
            "state (jharkhand)",
            "state (karnataka)",
            "state (kerala)",
            "state (madhya pradesh)",
            "state (maharashtra)",
            "state (manipur)",
            "state (meghalaya)",
            "state (mizoram)",
            "state (nagaland)",
            "state (odisha)",
            "state (punjab)",
            "state (rajasthan)",
            "state (sikkim)",
            "state (tamil nadu)",
            "state (telangana)",
            "state (tripura)",
            "state (uttar pradesh)",
            "state (uttarakhand)",
            "t (ladakh)",
            "ut (andaman and nicobar islands)",
            "ut (dnh and dd)",
            "ut (ladakh)",
            "ut (puducherry)",
            "z_test_cbse",
            "z_test_framework"
        ],
    },
];
